apiVersion: v1
kind: ConfigMap
metadata:
  name: kreutzer-core
  namespace: kreutzer
  annotations: { }
  labels:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": core
data:
  config.toml: |
    [server]
    host = "0.0.0.0"
    port = 8080
    grpc_port = 8081

    [database]
    host = "kreutzer-database"
    port = 5432
    username = "postgres"
    password = "${DB_PASSWORD}"

