apiVersion: v1
kind: Service
metadata:
  name: kreutzer-core
  namespace: kreutzer
  annotations: { }
  labels:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": core
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 8081
      targetPort: 8081
  selector:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": core
