apiVersion: v1
kind: Service
metadata:
  name: kreutzer-database
  namespace: kreutzer
  annotations: { }
  labels:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": database
spec:
  type: NodePort
  ports:
    - name: database
      port: 5432
      targetPort: 5432
      nodePort: 15432
  selector:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": database
