apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kreutzer-database
  namespace: kreutzer
  annotations: { }
  labels:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": database
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/name": kreutzer
      "app.kubernetes.io/component": database
  serviceName: kreutzer-database
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": kreutzer
        "app.kubernetes.io/component": database
    spec:
      initContainers:
        - name: data-permissions-ensurer
          image: "postgres:15.1-alpine"
          command:
            - /bin/sh
            - -c
          args:
            - chmod -R 700 /var/lib/postgresql/data/pgdata || true
          volumeMounts:
            - name: database-data
              mountPath: /var/lib/postgresql/data/pgdata
      containers:
        - name: database
          image: "postgres:15.1-alpine"
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          livenessProbe:
            tcpSocket:
              port: 5432
          readinessProbe:
            tcpSocket:
              port: 5432
          volumeMounts:
            - name: database-data
              mountPath: /var/lib/postgresql/data/pgdata
            - name: shm-volume
              mountPath: /dev/shm
      volumes:
        - name: database-data
          hostPath:
            path: /data/postgres/pgdata
        - name: shm-volume
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi

