apiVersion: v1
kind: ConfigMap
metadata:
  name: kreutzer-portal
  namespace: kreutzer
  annotations: { }
  labels:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": portal
data:
  nginx.conf: |-
    # Default nginx configuration for docker.

    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
      worker_connections  1024;
    }

    http {

      sendfile            on;
      tcp_nopush          on;
      tcp_nodelay         on;
      keepalive_timeout   65;

      types_hash_max_size 2048;
      include             /etc/nginx/mime.types;
      include             /etc/nginx/conf.d/*.conf;

      default_type        application/octet-stream;

      log_format  main  '$host $remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;

      # Gzip for static file.
      gzip               on;
      gzip_buffers       4 16k;
      gzip_comp_level    6;
      gzip_min_length    1k;
      gzip_types text/plain applcation/x-javascript application/javascript text/css text/xml application/xml application/xml+rss text/javascript application/x-httpd-php image/svg+xml image/*;
      gzip_static        on;
      gzip_vary          on;
      gzip_proxied       any;
      gzip_http_version  1.0;
      gzip_disable       "MSIE [1-6]\.";

      server {
        listen       80;
        server_name  localhost;

        proxy_set_header  Host            $host;
        proxy_set_header  X-Real-IP       $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
          if ($request_filename ~* .*\.(?:htm|html)$) {
            add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
            access_log on;
          }

          root   /usr/share/nginx/html;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
        }
      }
    }
