apiVersion: apps/v1
kind: Deployment
metadata:
  name: kreutzer-portal
  namespace: kreutzer
  annotations: { }
  labels:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": portal
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": kreutzer
      "app.kubernetes.io/component": portal
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": kreutzer
        "app.kubernetes.io/component": portal
    spec:
      containers:
        - name: portal
          image: nginx:alpine-slim
          ports:
            - containerPort: 80
              protocol: TCP
          resources: { }
          volumeMounts:
            - name: portal-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: portal-config
          configMap:
            name: kreutzer-portal
            defaultMode: 420

