apiVersion: v1
kind: Service
metadata:
  name: kreutzer-portal
  namespace: kreutzer
  annotations: { }
  labels:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": portal
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    "app.kubernetes.io/name": kreutzer
    "app.kubernetes.io/component": portal
